
version: '3'

networks:
  antiope:
    driver: bridge

services:
  keycloak:

    image: antiope
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
      ANTIOPE_CONFIG: Wwp7ICJyZWFsbU5hbWUiOiAicmVhbG0xIiwKICAiYnJva2VySXAiOiAia2Fma2EiLAogICJicm9rZXJQb3J0IjogIjkwOTIiLAogICJ0b3BpYyI6ICJ0b3BpYzEiLAoiY2xpZW50SWQiOiJjbGllbnQxIgoKfSwKeyAicmVhbG1OYW1lIjogInJlYWxtMiIsCiAgImJyb2tlcklwIjogImthZmthIiwKICAiYnJva2VyUG9ydCI6ICI5MDkyIiwKICAidG9waWMiOiAidG9waWMyIiAgLAoiY2xpZW50SWQiOiJjbGllbnQyIgogCn0KXQ==
    command: start-dev
    depends_on:
      - kafka
    networks:
      - antiope
    expose:
      - "8080"
    
  zookeeper:
    restart: always
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:    
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - antiope
      

  kafka:
    image: 'confluentinc/cp-kafka:7.2.6'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS=5000

    depends_on:
     - zookeeper
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -z -v -w5 localhost 9092" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - antiope

  kafkaui:
    container_name: kafkaui_local
    image: provectuslabs/kafka-ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: antiope.local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - '1234:8080'
    networks:
      - antiope
